version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: xenoxify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/xenoxify
      NODE_ENV: production
      JWT_SECRET: your_jwt_secret_key
      SHOPIFY_API_KEY: your_shopify_api_key
      SHOPIFY_API_SECRET: your_shopify_api_secret
      APP_URL: http://localhost:3001
      FRONTEND_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  worker:
    build: ./server
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/xenoxify
      NODE_ENV: production
      JWT_SECRET: your_jwt_secret_key
      SHOPIFY_API_KEY: your_shopify_api_key
      SHOPIFY_API_SECRET: your_shopify_api_secret
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run worker

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3001

volumes:
  postgres_data:

